version: '3.8'

services:
    jimbulo:
        build:
            args:
                user: jimbulo
                uid: 1008
            context: ./
            dockerfile: DockerFile
        restart: always
        image: jimbulo
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - jimbulo-network

    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        ports:
            - 8000:80
        networks:
            - jimbulo-network

    mysql:
        image: mysql:5.7.22
        restart: always
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3312:3306
        networks:
            - jimbulo-network

    queue:
        build:
            args:
                user: jimbulo
                uid: 1008
            context: ./
            dockerfile: DockerFile
        restart: always
        command: "php artisan queue:work --tries=20"
        volumes:
            - ./:/var/www
        networks:
            - jimbulo-network

networks:
    jimbulo-network:
        driver: bridge
