name: "rafael ferreira"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzv0 --delete"
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
